(ns sdk.aws.cognito-idp-test
  (:require [clojure.test :refer :all]
            [lambda.util :as utils]
            [aws :as aws]
            [lambda.util-test :as util-test]
            [lambda.test.fixture.client :as client]
            [lambda.util :as util]
            [sdk.aws.common :as common]
            [sdk.aws.cognito-idp :as cognito-idp]))

(def auth "sws-signature")

(def ctx
  {:aws {:aws-access-key-id "test-key-id"
         :aws-secret-access-key "secret-access-key-id"
         :region "eu-central-1"
         :aws-session-token "session-token"}
   :svc {:username "test-svc@internal"
         :password "AA33test-svc"}
   :auth {:user-pool-id util-test/user-pool-id
          :client-id util-test/user-pool-client-id
          :client-secret util-test/user-pool-client-secret}})

(def id-token "id-token")

(def login-request
  {:body "{\"Username\":\"PingFederate_robert.pofuk@rbinternational.com\",\"UserPoolId\":\"eu-central-1_ACXYul00Q\"}"
   :headers {"Authorization" "AWS4-HMAC-SHA256 Credential=test-key-id/20200504/eu-central-1/cognito-idp/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=8405706d7ca882dc744baa7e4da416e5785149e88a879b37a53445022a021ed1"
             "Content-Type" "application/x-amz-json-1.1"
             "X-Amz-Date" "20200504T080055Z"
             "X-Amz-Security-Token" "session-token"
             "X-Amz-Target" "AWSCognitoIdentityProviderService.AdminGetUser"}
   :method :post
   :timeout 5000
   :url "https://cognito-idp.eu-central-1.amazonaws.com"})

(def user-response
  {:Enabled true
   :UserAttributes [{:Name "sub"
                     :Value "168a796e-6287-4bac-8a40-fe3dafc99123"}
                    {:Name "identities"
                     :Value "[{\"userId\":\"robert.pofuk@rbinternational.com\",\"providerName\":\"PingFederate\",\"providerType\":\"OIDC\",\"issuer\":null,\"primary\":true,\"dateCreated\":1616863647306}]"}
                    {:Name "email_verified"
                     :Value "false"}
                    {:Name "profile"
                     :Value "[\"RBI-GLMS-T-Users\",\"RBI-GLMS-T-Lime-Risk-Managers\",\"RBI-GLMS-T-Lime-Account-Managers\"]"}
                    {:Name "given_name"
                     :Value "Robert"}
                    {:Name "family_name"
                     :Value "POFUK"}
                    {:Name "email"
                     :Value "robert.pofuk@rbinternational.com"}]
   :UserCreateDate 1.616863647313E9
   :UserLastModifiedDate 1.617219318244E9
   :UserStatus "EXTERNAL_PROVIDER"
   :Username "PingFederate_robert.pofuk@rbinternational.com"})

(deftest get-token-test
  (binding [util/*cache* (atom {})]
    (with-redefs [common/create-date (fn [] "20200504T080055Z")]
      (client/mock-http
       [{:post "https://cognito-idp.eu-central-1.amazonaws.com"
         :status 200
         :body (util/to-json user-response)}]
       (is (= user-response
              (cognito-idp/admin-get-user
               ctx
               {:username "PingFederate_robert.pofuk@rbinternational.com"})))
       (client/verify-traffic [login-request])))))

(def user-groups-request
  {:body "{\"Username\":\"PingFederate_robert.pofuk@rbinternational.com\",\"UserPoolId\":\"eu-central-1_ACXYul00Q\",\"Limit\":60}"
   :headers {"Authorization" "AWS4-HMAC-SHA256 Credential=test-key-id/20200504/eu-central-1/cognito-idp/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=a2e3fe42e49b7ac3fbc468588a14ad8ce1cd46678107c66158c466fedd20b1dc"
             "Content-Type" "application/x-amz-json-1.1"
             "X-Amz-Date" "20200504T080055Z"
             "X-Amz-Security-Token" "session-token"
             "X-Amz-Target" "AWSCognitoIdentityProviderService.AdminListGroupsForUser"}
   :method :post
   :timeout 5000
   :url "https://cognito-idp.eu-central-1.amazonaws.com"})

(def user-groups-response
  {:Groups [{:CreationDate 1.590473830744E9
             :Description "Account Managers"
             :GroupName "lime-account-managers"
             :LastModifiedDate 1.590473830744E9
             :UserPoolId "eu-central-1_tk6YrMrPc"}
            {:CreationDate 1.590473832758E9
             :Description "Risk Managers"
             :GroupName "lime-risk-managers"
             :LastModifiedDate 1.590473832758E9
             :UserPoolId "eu-central-1_tk6YrMrPc"}
            {:CreationDate 1.590473833703E9
             :Description "Autogenerated group for users who sign in using PingFederate"
             :GroupName "eu-central-1_tk6YrMrPc_PingFederate"
             :LastModifiedDate 1.590473833703E9
             :UserPoolId "eu-central-1_tk6YrMrPc"}
            {:CreationDate 1.616767353844E9
             :Description "Test realm"
             :GroupName "realm-test"
             :LastModifiedDate 1.616767353844E9
             :UserPoolId "eu-central-1_tk6YrMrPc"}]})

(deftest get-users-for-group-test
  (binding [util/*cache* (atom {})]
    (with-redefs [common/create-date (fn [] "20200504T080055Z")]
      (client/mock-http
       [{:post "https://cognito-idp.eu-central-1.amazonaws.com"
         :status 200
         :body (util/to-json user-groups-response)}]
       (is (= user-groups-response
              (cognito-idp/admin-list-groups-for-user
               ctx
               {:username "PingFederate_robert.pofuk@rbinternational.com"})))
       (client/verify-traffic [user-groups-request])))))
