version: "3.8"

services:

  clojure:
    image: ${DOCKER_URL}/${DOCKER_ORG}/cljlambda-img:b1449
    networks:
      - rbi
    volumes:
      - .:/build
    environment:
      - CI=true
      - TEST=true
    working_dir: /build
    depends_on:
      - postgres
    command: ["clojure", "-M:local:dev:test:nrepl"]
