ARG DOCKER_URL=""
FROM ${DOCKER_URL}library/postgres:17

RUN apt-get update \
    && apt-get install -y postgresql-17-cron \
    && rm -rf /var/lib/apt/lists/*

CMD ["postgres", "-E", "-c", "shared_preload_libraries=pg_cron", "-c", "cron.database_name=postgres"]
