- hosts: localhost
  connection: local
  tasks: 
    - debug: 
        msg: 'Creating stuff needed for IT'
    - name: 'Create it test bucket'
      amazon.aws.s3_bucket:
        name: '{{ lookup("env", "AccountId") }}-{{ lookup("env", "EnvironmentNameLower") }}-it'
        state: present
        encryption: "AES256"
        public_access:
          block_public_acls: true
          ignore_public_acls: true
          block_public_policy: true
          restrict_public_buckets: true

    - name: 'Create sqs bucket'
      amazon.aws.s3_bucket:
        name: '{{ lookup("env", "AccountId") }}-{{ lookup("env", "EnvironmentNameLower") }}-sqs'
        state: present
        encryption: "AES256"
        public_access:
          block_public_acls: true
          ignore_public_acls: true
          block_public_policy: true
          restrict_public_buckets: true

    - name: Create standard queueu
      community.aws.sqs_queue:
        name: '{{ lookup("env", "AccountId") }}-{{ lookup("env", "EnvironmentNameLower") }}-it'
        region: '{{ lookup("env", "Region") }}'
        default_visibility_timeout: 120
        message_retention_period: 86400
        policy:
           Version: 2012-10-17
           Id: 'it-policy'
           Statement:
             - Sid: allowSend
               Effect: Allow
               Principal:
                 AWS: 'arn:aws:iam::{{ lookup("env", "AccountId") }}:root'
               Action:
                 - SQS:SendMessage
               Resource: 'arn:aws:sqs:*:*:{{ lookup("env", "AccountId") }}-{{ lookup("env", "EnvironmentNameLower") }}-it'


    - name: Create fifo queue
      community.aws.sqs_queue:
        name: '{{ lookup("env", "EnvironmentNameLower") }}-it.fifo'
        region: '{{ lookup("env", "Region") }}'
        default_visibility_timeout: 120
        message_retention_period: 86400
        queue_type: fifo
        policy:
           Version: 2012-10-17
           Id: 'it-fifo-policy'
           Statement:
             - Sid: allowSend
               Effect: Allow
               Principal:
                 AWS: 'arn:aws:iam::{{ lookup("env", "AccountId") }}:root'
               Action:
                 - SQS:SendMessage
               Resource: 'arn:aws:sqs:*:*:{{ lookup("env", "AccountId") }}-{{ lookup("env", "EnvironmentNameLower") }}-it'

