name: clj-holmes-scan

on:
  push:
    branches: [staging]
  pull_request:
    branches: [ master ]

jobs:
  clj-holmes-action:
    uses: raiffeisen-group-open-source/rbi-opensource-actions/.github/workflows/clj-holmes.yml@master
    secrets:
      PUBLIC_TOKEN: ${{ secrets.PUBLIC_TOKEN }}
      PUBLIC_USERNAME: ${{ secrets.PUBLIC_USERNAME }}


